<template>
  <section class="profile"><article class="visual"><span>Fulfillment Transit</span><div class="art"><div class="scanner"></div><div class="box"></div><div class="line"></div></div><h1>Профиль рабочего</h1><p>Доступ к QR-операциям, приёмке и смене статусов.</p></article><article class="info"><p>Аккаунт</p><h2>{{ user?.full_name || 'Рабочий склада' }}</h2><div class="rows"><div><span>ФИО</span><b>{{ user?.full_name || '—' }}</b></div><div><span>Email</span><b>{{ user?.email || '—' }}</b></div><div><span>Телефон</span><b>{{ user?.phone || '—' }}</b></div><div><span>Роль</span><b>Рабочий склада</b></div></div><button @click="logout">Выйти из аккаунта</button></article></section>
</template>
<script setup>
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { clearAuth, getCurrentUser, loadMe } from '@/shared/api/http'
const router=useRouter(), user=ref(getCurrentUser()); function logout(){clearAuth();router.push('/login')} onMounted(async()=>{try{user.value=await loadMe()}catch{user.value=getCurrentUser()}})
</script>
<style scoped>
.profile{display:grid;grid-template-columns:minmax(360px,.8fr) minmax(520px,1fr);gap:28px}.visual,.info{border-radius:36px;box-shadow:0 34px 80px rgba(0,0,0,.16)}.visual{padding:34px;background:radial-gradient(circle at 12% 0,rgba(255,63,76,.34),transparent 32rem),radial-gradient(circle at 100% 20%,rgba(0,188,212,.24),transparent 26rem),#07101f;color:white}.visual>span{display:inline-flex;padding:16px 18px;border-radius:18px;background:rgba(255,255,255,.08);color:#ff9aa2;font-weight:950;letter-spacing:.28em;text-transform:uppercase}.art{position:relative;height:330px;margin:34px 0;border:1px solid rgba(255,255,255,.12);border-radius:30px;background:rgba(255,255,255,.04);overflow:hidden}.scanner{position:absolute;width:140px;height:170px;left:62px;top:62px;border-radius:34px;border:7px solid #ff7b85}.scanner:before{content:'';position:absolute;left:20px;top:42px;width:86px;height:8px;border-radius:999px;background:#fff;box-shadow:0 34px 0 #fff}.box{position:absolute;width:160px;height:120px;right:64px;top:100px;border-radius:26px;background:#263449}.box:before{content:'QR';position:absolute;inset:34px;display:grid;place-items:center;border-radius:18px;background:#ff3f4c;color:white;font-weight:950}.line{position:absolute;width:70%;height:7px;left:15%;bottom:64px;border-radius:999px;background:rgba(255,255,255,.34)}.visual h1{margin:0;font-size:clamp(42px,6vw,74px);line-height:.95;font-weight:950}.visual p{max-width:620px;color:#d7e4f4;font-size:19px;line-height:1.6}.info{padding:42px;background:white;color:#07101f}.info>p{margin:0 0 12px;color:#ff3f4c;font-weight:950;letter-spacing:.38em;text-transform:uppercase}.info h2{margin:0 0 28px;font-size:clamp(42px,5vw,72px);line-height:.9;font-weight:950}.rows{display:grid;gap:14px}.rows div{display:grid;grid-template-columns:160px 1fr;gap:18px;align-items:center;padding:20px;border:1px solid #dce5f0;border-radius:22px;background:#f7faff}.rows span{color:#94a3b8;font-size:13px;font-weight:950;letter-spacing:.26em;text-transform:uppercase}.rows b{font-size:20px;font-weight:950}button{width:100%;min-height:66px;margin-top:24px;border:0;border-radius:22px;background:#07101f;color:white;font:inherit;font-weight:950;cursor:pointer}@media(max-width:1060px){.profile{grid-template-columns:1fr}}
</style>
