<template>
  <section class="page">
    <div class="hero"><p>QR-операция</p><h1>Сканирование грузового места</h1><span>Введите QR-код вручную. После проверки можно сразу сменить статус.</span><div class="scan"><input v-model="qrCode" placeholder="QR-TPRO-MSK-240001" @keydown.enter="scan"/><button @click="scan">Проверить QR</button></div><p v-if="error" class="error">{{ error }}</p></div>
    <article v-if="cargoItem" class="card"><header><div><p>Грузовое место</p><h2>{{ cargoItem.qr_code || `Груз #${cargoItem.id}` }}</h2></div><span>{{ cargoStatusLabel(cargoItem.status) }}</span></header><dl><div><dt>Заявка</dt><dd>#{{ cargoItem.order_id || '—' }}</dd></div><div><dt>Зона</dt><dd>#{{ cargoItem.storage_zone_id || '—' }}</dd></div><div><dt>Гейт</dt><dd>#{{ cargoItem.gate_id || '—' }}</dd></div><div><dt>Обновлено</dt><dd>{{ formatDateTime(cargoItem.updated_at || cargoItem.created_at) }}</dd></div></dl><div class="op"><BaseSelect v-model="form.status" :options="workerCargoStatusOptions" label="Новый статус"/><textarea v-model="form.comment" placeholder="Комментарий операции"></textarea><button @click="updateStatus">Сохранить статус</button></div></article>
  </section>
</template>
<script setup>
import { reactive, ref } from 'vue'
import { apiFetch } from '@/shared/api/http'
import BaseSelect from '@/shared/ui/BaseSelect.vue'
import { cargoStatusLabel, formatDateTime, workerCargoStatusOptions } from './workerUtils'
const qrCode=ref('QR-TPRO-MSK-240001'), cargoItem=ref(null), error=ref('')
const form=reactive({status:'received',comment:''})
async function scan(){const v=qrCode.value.trim(); if(!v){error.value='Введите QR-код.';return} error.value=''; try{const d=await apiFetch(`/cargo-items/scan?qr_code=${encodeURIComponent(v)}`,{auth:true}); cargoItem.value=d.cargo_item||d; form.status=cargoItem.value?.status||'received'}catch(e){error.value=e.message||'Не удалось проверить QR'}}
async function updateStatus(){if(!cargoItem.value?.id)return; await apiFetch(`/cargo-items/${cargoItem.value.id}/status`,{method:'PATCH',auth:true,body:{status:form.status,comment:form.comment?.trim()||null}}); form.comment=''; await scan()}
</script>
<style scoped>
.page{display:grid;gap:24px}.hero,.card{border-radius:34px;background:rgba(255,255,255,.96);color:#07101f;box-shadow:0 34px 80px rgba(0,0,0,.16)}.hero{padding:38px}.hero p,.card header p{margin:0 0 12px;color:#ff3f4c;font-weight:950;letter-spacing:.34em;text-transform:uppercase}.hero h1{margin:0;font-size:clamp(44px,7vw,84px);line-height:.9;font-weight:950}.hero span{display:block;max-width:860px;margin-top:20px;color:#596b84;font-size:20px}.scan{display:grid;grid-template-columns:1fr auto;gap:14px;margin-top:28px}input,textarea{width:100%;border:1px solid #dce5f0;border-radius:22px;background:#f7faff;color:#07101f;font:inherit;font-weight:950;outline:none}input{min-height:68px;padding:0 22px}textarea{min-height:68px;padding:20px;resize:vertical}button{min-height:68px;border:0;border-radius:22px;background:#ff3f4c;color:white;font:inherit;font-weight:950;padding:0 28px;cursor:pointer}.error{margin-top:18px;padding:16px;border-radius:18px;background:#fff0f2;color:#ff3f4c!important;letter-spacing:0!important;text-transform:none!important}.card{padding:28px}.card header{display:flex;justify-content:space-between;gap:18px;margin-bottom:18px}.card h2{margin:0;font-size:36px;font-weight:950}.card header span{align-self:flex-start;padding:12px 16px;border-radius:16px;background:#fff0f2;color:#ff3f4c;font-weight:950}dl{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:0 0 18px}dl div{padding:16px;border-radius:18px;background:#f4f7fb}dt{color:#93a4bb;font-size:12px;font-weight:950;letter-spacing:.22em;text-transform:uppercase}dd{margin:8px 0 0;font-weight:950}.op{display:grid;grid-template-columns:1fr 1fr auto;gap:14px;align-items:end;padding:18px;border-radius:24px;background:#f8fafc}@media(max-width:980px){.scan,.op,dl{grid-template-columns:1fr}}
</style>
