const DEFAULT_API_BASE_URL = '/api/v1'
function normalizeBaseUrl(value) { const raw = value || DEFAULT_API_BASE_URL; return raw.includes('localhost:8080') || raw.includes('127.0.0.1:8080') ? DEFAULT_API_BASE_URL : raw.replace(/\/+$/, '') }
export const API_BASE_URL = normalizeBaseUrl(import.meta.env.VITE_API_BASE_URL)
function buildUrl(path) { if (/^https?:\/\//i.test(path)) return path; return `${API_BASE_URL}${path?.startsWith('/') ? path : `/${path}`}` }
function parseJwtPayload(token) { try { const [,p]=String(token).split('.'); if(!p)return null; return JSON.parse(decodeURIComponent(atob(p.replace(/-/g,'+').replace(/_/g,'/')).split('').map(c=>`%${c.charCodeAt(0).toString(16).padStart(2,'0')}`).join(''))) } catch { return null } }
export function getAccessToken(){return localStorage.getItem('access_token')||''}
export function getRefreshToken(){return localStorage.getItem('refresh_token')||''}
export function getCurrentUser(){try{const raw=localStorage.getItem('current_user'); return raw?JSON.parse(raw):null}catch{return null}}
export function getCurrentRole(){return String(getCurrentUser()?.role||'').toLowerCase()}
export function clearAuth(){localStorage.removeItem('access_token');localStorage.removeItem('refresh_token');localStorage.removeItem('current_user')}
function normalizeUser(payload, token){const u=payload?.user||payload?.me||payload?.profile||payload||null; if(u&&typeof u==='object'&&(u.email||u.full_name||u.role))return {...u,role:String(u.role||'').toLowerCase()}; const p=token?parseJwtPayload(token):null; return p?{id:p.user_id||p.sub||p.id,email:p.email||'',full_name:p.full_name||p.name||p.email||'Пользователь',role:String(p.role||'').toLowerCase()}:null}
export function saveAuth(payload={}){const accessToken=payload.access_token||payload.accessToken||payload.token||payload.tokens?.access_token||payload.tokens?.accessToken||''; const refreshToken=payload.refresh_token||payload.refreshToken||payload.tokens?.refresh_token||payload.tokens?.refreshToken||''; if(accessToken)localStorage.setItem('access_token',accessToken); if(refreshToken)localStorage.setItem('refresh_token',refreshToken); const user=normalizeUser(payload,accessToken); if(user)localStorage.setItem('current_user',JSON.stringify(user)); return {accessToken,refreshToken,user}}
export function cabinetPathByRole(role){const r=String(role||'').toLowerCase(); if(r==='worker'||r==='warehouse_worker')return '/worker'; if(r==='logist'||r==='admin'||r==='logistician')return '/logist'; return '/client'}
export async function apiFetch(path, options={}){const {method='GET',body,auth=false,headers={}}=options; const h=new Headers(headers); let requestBody=body; if(body!==undefined&&body!==null&&!(body instanceof FormData)){if(!h.has('Content-Type'))h.set('Content-Type','application/json'); requestBody=typeof body==='string'?body:JSON.stringify(body)} if(auth){const t=getAccessToken(); if(t)h.set('Authorization',`Bearer ${t}`)} const res=await fetch(buildUrl(path),{method,headers:h,body:requestBody}); const text=await res.text(); let data=null; if(text){try{data=JSON.parse(text)}catch{data={message:text}}} if(!res.ok){const e=new Error(data?.error||data?.message||data?.detail||`HTTP ${res.status}`); e.status=res.status; e.data=data; throw e} return data}
export async function loadMe(){const data=await apiFetch('/auth/me',{auth:true}); const user=normalizeUser(data,getAccessToken()); if(user)localStorage.setItem('current_user',JSON.stringify(user)); return user}
